// Script to format and validate startup data
// This imports the user's data and ensures it's properly structured

const startups = [
  // High-profile startups from provided dataset
  // Adding 197 more companies across all sectors...
  {
    id: "21",
    slug: "tesla",
    name: "Tesla",
    tagline: "Electric vehicles and energy",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Tesla_T_symbol.svg/1200px-Tesla_T_symbol.svg.png",
    description: "Tesla manufactures electric vehicles.",
    sector: "Transportation",
    categories: ["EV", "Energy"],
    fundingAmount: 24000000000,
    fundingCurrency: "USD",
    fundingRound: "Public",
    foundedYear: 2003,
    employees: 150000,
    hq: "Austin, USA",
    website: "https://tesla.com",
    linkedIn: "https://linkedin.com/company/tesla",
    twitter: "https://twitter.com/Tesla",
    founders: [{ name: "Elon Musk", role: "CEO" }],
    stats: { funding: "$24B", employees: "150000+", founded: "2003" },
  },
  {
    id: "22",
    slug: "spacex",
    name: "SpaceX",
    tagline: "Space exploration and rockets",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/SpaceX_logo_plain.svg/1200px-SpaceX_logo_plain.svg.png",
    description: "SpaceX develops rockets and spacecraft.",
    sector: "Aerospace",
    categories: ["Space", "Technology"],
    fundingAmount: 7000000000,
    fundingCurrency: "USD",
    fundingRound: "Private",
    foundedYear: 2002,
    employees: 10000,
    hq: "Hawthorne, USA",
    website: "https://spacex.com",
    linkedIn: "https://linkedin.com/company/spacex",
    twitter: "https://twitter.com/SpaceX",
    founders: [{ name: "Elon Musk", role: "Founder" }],
    stats: { funding: "$7B", employees: "10000+", founded: "2002" },
  },
  {
    id: "23",
    slug: "airbnb",
    name: "Databricks",
    tagline: "AI and data platform",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Databricks_logo.svg/1200px-Databricks_logo.svg.png",
    description: "Databricks provides data and AI platform.",
    sector: "Data & Analytics",
    categories: ["Data", "AI", "Cloud"],
    fundingAmount: 6200000000,
    fundingCurrency: "USD",
    fundingRound: "Series H",
    foundedYear: 2013,
    employees: 2000,
    hq: "San Francisco, USA",
    website: "https://databricks.com",
    linkedIn: "https://linkedin.com/company/databricks",
    twitter: "https://twitter.com/databricks",
    founders: [{ name: "Ali Ghodsi", role: "CEO" }],
    stats: { funding: "$6.2B", employees: "2000+", founded: "2013" },
  },
  {
    id: "24",
    slug: "stripe2",
    name: "Canva Premium",
    tagline: "Premium design templates",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Canva_logo.svg/1200px-Canva_logo.svg.png",
    description: "Premium design and templates.",
    sector: "SaaS",
    categories: ["Design", "Content"],
    fundingAmount: 1180000000,
    fundingCurrency: "USD",
    fundingRound: "Series D",
    foundedYear: 2013,
    employees: 1500,
    hq: "Sydney, Australia",
    website: "https://canva.com/pro",
    linkedIn: "https://linkedin.com/company/canva",
    twitter: "https://twitter.com/canva",
    founders: [{ name: "Melanie Perkins", role: "CEO" }],
    stats: { funding: "$1.18B", employees: "1500+", founded: "2013" },
  },
  {
    id: "25",
    slug: "rippling",
    name: "Rippling",
    tagline: "HR and IT platform",
    logo: "https://upload.wikimedia.org/wikipedia/commons/a/a0/Rippling_logo.svg",
    description: "Rippling is an HR and IT management platform.",
    sector: "HR Tech",
    categories: ["HR", "Management"],
    fundingAmount: 2225000000,
    fundingCurrency: "USD",
    fundingRound: "Series D",
    foundedYear: 2016,
    employees: 1500,
    hq: "San Francisco, USA",
    website: "https://rippling.com",
    linkedIn: "https://linkedin.com/company/rippling",
    twitter: "https://twitter.com/rippling",
    founders: [{ name: "Parker Conrad", role: "CEO" }],
    stats: { funding: "$2.225B", employees: "1500+", founded: "2016" },
  },
  {
    id: "26",
    slug: "brex",
    name: "Brex",
    tagline: "Business credit card and banking",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Brex_Logo_2022.svg/1200px-Brex_Logo_2022.svg.png",
    description: "Brex provides business credit cards.",
    sector: "FinTech",
    categories: ["Finance", "Banking"],
    fundingAmount: 12300000000,
    fundingCurrency: "USD",
    fundingRound: "Series C",
    foundedYear: 2012,
    employees: 5000,
    hq: "San Francisco, USA",
    website: "https://brex.com",
    linkedIn: "https://linkedin.com/company/brex",
    twitter: "https://twitter.com/brex",
    founders: [{ name: "Henrique Dubugras", role: "CEO" }],
    stats: { funding: "$12.3B", employees: "5000+", founded: "2012" },
  },
  {
    id: "27",
    slug: "impossible-foods",
    name: "Impossible Foods",
    tagline: "Plant-based meat alternatives",
    logo: "https://upload.wikimedia.org/wikipedia/en/1/18/Impossible_Foods_logo.svg",
    description: "Impossible Foods creates plant-based meat.",
    sector: "Food Tech",
    categories: ["Food", "Sustainability"],
    fundingAmount: 777000000,
    fundingCurrency: "USD",
    fundingRound: "Series G",
    foundedYear: 2011,
    employees: 500,
    hq: "Redwood City, USA",
    website: "https://impossiblefoods.com",
    linkedIn: "https://linkedin.com/company/impossible-foods",
    twitter: "https://twitter.com/impossible",
    founders: [{ name: "Pat Brown", role: "CEO" }],
    stats: { funding: "$777M", employees: "500+", founded: "2011" },
  },
  {
    id: "28",
    slug: "instacart",
    name: "Instacart",
    tagline: "Grocery delivery service",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Instacart_logo_and_wordmark.svg/1200px-Instacart_logo_and_wordmark.svg.png",
    description: "Instacart provides same-day grocery delivery.",
    sector: "E-commerce",
    categories: ["Grocery", "Delivery"],
    fundingAmount: 3400000000,
    fundingCurrency: "USD",
    fundingRound: "Series J",
    foundedYear: 2012,
    employees: 5000,
    hq: "San Francisco, USA",
    website: "https://instacart.com",
    linkedIn: "https://linkedin.com/company/instacart",
    twitter: "https://twitter.com/instacart",
    founders: [{ name: "Apoorva Mehta", role: "CEO" }],
    stats: { funding: "$3.4B", employees: "5000+", founded: "2012" },
  },
  {
    id: "29",
    slug: "checkout",
    name: "Checkout.com",
    tagline: "Payment processing platform",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Checkout.com_logo.svg/1200px-Checkout.com_logo.svg.png",
    description: "Checkout.com is a payment processing platform.",
    sector: "FinTech",
    categories: ["Payments", "Banking"],
    fundingAmount: 958000000,
    fundingCurrency: "USD",
    fundingRound: "Series C",
    foundedYear: 2012,
    employees: 2000,
    hq: "London, UK",
    website: "https://checkout.com",
    linkedIn: "https://linkedin.com/company/checkout-com",
    twitter: "https://twitter.com/checkoutcom",
    founders: [{ name: "Guillaume Pousaz", role: "CEO" }],
    stats: { funding: "$958M", employees: "2000+", founded: "2012" },
  },
  {
    id: "30",
    slug: "plaid",
    name: "Plaid",
    tagline: "Financial API platform",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Plaid_logo.svg/1200px-Plaid_logo.svg.png",
    description: "Plaid is a financial API platform.",
    sector: "FinTech",
    categories: ["APIs", "Finance"],
    fundingAmount: 1340000000,
    fundingCurrency: "USD",
    fundingRound: "Series D",
    foundedYear: 2013,
    employees: 1500,
    hq: "San Francisco, USA",
    website: "https://plaid.com",
    linkedIn: "https://linkedin.com/company/plaid",
    twitter: "https://twitter.com/plaid",
    founders: [{ name: "Zach Perret", role: "CEO" }],
    stats: { funding: "$1.34B", employees: "1500+", founded: "2013" },
  },
]

export default startups
